#1. 고양이와 개는 몇 마리 있을까

SELECT ANIMAL_TYPE
        , COUNT(ANIMAL_TYPE)
FROM ANIMAL_INS
GROUP BY ANIMAL_TYPE
ORDER BY ANIMAL_TYPE


#2. 동명 동물 수 찾기

SELECT NAME, COUNT(NAME) AS COUNT
FROM ANIMAL_INS
GROUP BY NAME
HAVING COUNT(NAME) >= 2
ORDER BY NAME


#3. 입양 시각 구하기(1)

SELECT DATE_FORMAT(DATETIME, '%H') AS HOUR
        , COUNT(ANIMAL_ID)
FROM ANIMAL_OUTS
WHERE DATE_FORMAT(DATETIME, '%H') >= 9 AND DATE_FORMAT(DATETIME, '%H') < 20
GROUP BY DATE_FORMAT(DATETIME, '%H')
ORDER BY HOUR


#4. 입양 시각 구하기(2)

WITH RECURSIVE HOUR AS(
SELECT 0 AS h 
UNION ALL 
SELECT h+1 FROM HOUR WHERE h<23)

SELECT h AS HOUR
         , COALESCE(COUNT(ANIMAL_ID),0) AS COUNT
FROM HOUR 
    LEFT JOIN ANIMAL_OUTS OUTS ON HOUR.h = HOUR(OUTS.DATETIME)
GROUP BY HOUR.h
