#1. 루시와 엘라 찾기

SELECT ANIMAL_ID
        , NAME
        , SEX_UPON_INTAKE
FROM ANIMAL_INS
WHERE NAME IN ('Lucy', 'Ella', 'Pickle', 'Rogan', 'Sabrina', 'Mitty')


#2. 이름에 el이 들어가는 동물 찾기

SELECT ANIMAL_ID
        , NAME
FROM ANIMAL_INS
WHERE NAME LIKE '%EL%' AND ANIMAL_TYPE = 'Dog'
ORDER BY NAME


#3. 중성화 여부 파악하기

SELECT ANIMAL_ID
        , NAME
        , CASE WHEN SEX_UPON_INTAKE LIKE '%Neutered%' THEN 'O'
                WHEN SEX_UPON_INTAKE LIKE '%Spayed%' THEN 'O'
                ELSE 'X' END AS SEX_UPON_INTAKE
FROM ANIMAL_INS
ORDER BY ANIMAL_ID


#4. 오랜 기간 보호한 동물(2)

SELECT ANIMAL_INS.ANIMAL_ID
        , ANIMAL_INS.NAME
FROM ANIMAL_INS
    INNER JOIN ANIMAL_OUTS ON ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
ORDER BY DATEDIFF(ANIMAL_OUTS.DATETIME, ANIMAL_INS.DATETIME) DESC
LIMIT 2


#5. DATETIME에서 DATE로 형 변환

SELECT ANIMAL_ID
        , NAME
        , DATE_FORMAT(DATETIME, '%Y-%m-%d') AS '날짜'
FROM ANIMAL_INS
ORDER BY ANIMAL_ID

